configuration: Release
init: tzutil /s "Eastern Standard Time"
nuget:
  account_feed: true
  disable_publish_on_pr: true
skip_tags: true
cache:
  - packages
  - C:\ProgramData\chocolatey\bin -> build.cake
  - C:\ProgramData\chocolatey\lib -> build.cake
  - tools -> build.cake
skip_branch_with_pr: true
build_script:
- cmd: >-
    choco install cake.portable -r -y

    cake
artifacts:
  path: Artifacts\*.nupkg
